# Generated by Django 1.9.6 on 2016-06-03 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0014_removed_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='field_of_study',
            field=models.TextField(blank=True, null=True),
        ),
    ]
