# Generated by Django 1.10.3 on 2017-01-02 21:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0026_profile_image_medium'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='linkedin',
        ),
    ]
