# Generated by Django 5.2.9 on 2026-01-07 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0036_set_fake_user_for_test_profiles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='edx_language_proficiencies',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='edx_requires_parental_consent',
            field=models.BooleanField(null=True),
        ),
    ]
