# Set Ruby as the language so it doesn't download the pip things. Instead, let docker do that.
language: ruby
cache: bundler
install:
  - docker-compose -f travis-docker-compose.yml build
  - docker-compose -f travis-docker-compose.yml run watch npm install --quiet

script:
  - docker-compose -f travis-docker-compose.yml run web tox
  - docker-compose -f travis-docker-compose.yml run watch npm run-script coverage
  - docker-compose -f travis-docker-compose.yml run watch npm run-script lint
  - docker-compose -f travis-docker-compose.yml run watch npm run-script scss_lint
  - docker-compose -f travis-docker-compose.yml run watch npm run-script flow
  - docker-compose -f travis-docker-compose.yml run watch ./webpack_if_prod.sh
services:
  - docker
