sudo: false
# Set Ruby as the language so it doesn't download the pip things. Instead, let docker do that.
language: ruby

matrix:
  include:
    - install:
      - env | grep TRAVIS > .env
      - env | grep CI >> .env
      - docker-compose -f travis-docker-compose.yml run celery echo
      script: (docker-compose -f travis-docker-compose.yml up celery &); sleep 5; docker-compose -f travis-docker-compose.yml run web tox
      services:
        - docker
      env:
        name: Python
    - install:
      - env | grep TRAVIS > .env
      - env | grep CI >> .env
      - docker build -t travis-watch -f ./travis/Dockerfile-travis-watch .
      - docker run --name travis-watch-container --env-file .env -e NODE_ENV=production -t travis-watch ./webpack_if_prod.sh
      - docker cp travis-watch-container:/src/webpack-stats.json .
      - docker cp travis-watch-container:/src/static/bundles ./static/bundles
      script: docker-compose -f travis-docker-compose.yml run -e DEBUG=False -e DJANGO_LIVE_TEST_SERVER_ADDRESS=0.0.0.0:7000-8000 selenium py.test ./selenium_tests
      services:
        - docker
      env:
        name: Python-Selenium
    - install:
      language: node_js
      cache: yarn
      node_js:
        - "6"
      script:
        - npm run coverage
        - npm run lint
        - npm run scss_lint
        - npm run flow
        - NODE_ENV=production ./webpack_if_prod.sh
      env:
        name: JavaScript
