version: '2.1'
services:
  python:
    volumes:
      - .:/src
      - django_media:/var/media

  nginx:
    volumes:
      - ./config/nginx.conf:/etc/nginx/conf.d/web.conf
      - ./:/src

  sftp:
    volumes:
      - sftp_share:/home/odl/results

  watch:
    volumes:
      - .:/src
      - yarn-cache:/home/mitodl/.cache/yarn


volumes:
  django_media: {}
  sftp_share: {}
  yarn-cache: {}
