version: '2.1'
services:
  python:
    build:
      context: .
      dockerfile: ./travis/Dockerfile-travis-web
    environment:
      DEBUG: 'False'
      NODE_ENV: 'production'

      # for celery, to avoid ImproperlyConfigured
      MAILGUN_URL: 'http://fake.example.com'
      MAILGUN_KEY: 'fake'
