FROM node:22.20.0-bullseye

LABEL maintainer "ODL DevOps <mitx-devops@mit.edu>"

RUN apt-get update && apt-get install libelf1

COPY package.json /src/

COPY scripts /src/scripts

RUN mkdir -p /home/node/.cache/yarn

RUN chown node:node /home/node/.cache/yarn

USER node
