version: '2'
services:
  db:
    image: postgres
    ports:
      - "5432"

  redis:
    image: redis
    ports:
      - "6379"

  python:
    build:
      context: .
      dockerfile: ./travis/Dockerfile-travis-web
    command: /bin/true
    environment:
      DEBUG: 'False'
      COVERAGE_DIR: htmlcov
      PORT: 8079
      NODE_ENV: 'production'
      DATABASE_URL: postgres://postgres@db:5432/postgres
      MICROMASTERS_SECURE_SSL_REDIRECT: 'False'
      MICROMASTERS_DB_DISABLE_SSL: 'True'
      ELASTICSEARCH_URL: elastic:9200
      BROKER_URL: redis://redis:6379/4
      CELERY_RESULT_BACKEND: redis://redis:6379/4
    env_file: .env

  web:
    image: micromasters_python
    extends:
      service: python
    command: >
      /bin/bash -c '
      sleep 3 &&
      python3 manage.py migrate &&
      ./with_host.sh python3 manage.py runserver 0.0.0.0:8079'
    ports:
      - "8079:8079"
    links:
      - db
      - elastic

  celery:
    image: micromasters_python
    extends:
      service: python
    command: >
      /bin/bash -c '
      sleep 3;
      celery -A micromasters worker -B -l debug'
    links:
      - db
      - elastic
      - redis

  elastic:
    image: elasticsearch:2.4.1
    command: elasticsearch -Des.network.host=0.0.0.0
    ports:
      - "9200"

  selenium:
    image: micromasters_python
    extends:
      service: python
    links:
      - db
      - elastic
      - redis

  grid:
    image: elgalu/selenium
