# Generated by Django 1.9.6 on 2016-06-09 16:26

from django.db import migrations
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0009_programpage_background_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='programpage',
            name='contact_us',
            field=wagtail.fields.RichTextField(blank=True),
        ),
    ]
