# Generated by Django 1.9.6 on 2016-06-09 16:28

from django.db import migrations
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0010_programpage_contact_us'),
    ]

    operations = [
        migrations.AddField(
            model_name='programpage',
            name='title_over_image',
            field=wagtail.fields.RichTextField(blank=True),
        ),
    ]
