# Generated by Django 1.9.7 on 2016-06-29 16:12

from django.db import migrations
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0013_programpage_thumbnail_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='frequentlyaskedquestion',
            name='answer',
            field=wagtail.fields.RichTextField(),
        ),
    ]
