# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-10-04 22:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0018_update_programfaculty'),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'FAQ Category',
                'ordering': ['name'],
                'verbose_name_plural': 'FAQ Categories',
            },
        ),
        migrations.AddField(
            model_name='frequentlyaskedquestion',
            name='category',
            field=modelcluster.fields.ParentalKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='faqs', to='cms.FAQCategory'),
        ),
    ]
