# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-10-05 16:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0018_update_programfaculty'),
    ]

    operations = [
        migrations.AddField(
            model_name='frequentlyaskedquestion',
            name='category',
            field=models.CharField(blank=True, help_text='Category for question. Questions with the same category will be grouped together when displayed.', max_length=255),
        ),
    ]
