# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-21 19:26
from __future__ import unicode_literals

from django.db import migrations

from django.utils.text import slugify
import itertools


def gen_unique_slug(apps, schema_editor):
    FrequentlyAskedQuestion = apps.get_model('cms', 'FrequentlyAskedQuestion')
    for row in FrequentlyAskedQuestion.objects.all():
        if not row.slug:
            for x in itertools.count(1):
                row.slug = orig = slugify(row.question)
                if not FrequentlyAskedQuestion.objects.filter(slug=row.slug).exists():
                    break
                row.slug = '%s-%d' % (orig, x)
        row.save()


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0026_frequentlyaskedquestion_slug'),
    ]

    operations = [
        migrations.RunPython(gen_unique_slug, reverse_code=migrations.RunPython.noop)
    ]
