# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-21 19:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0027_populate_slug_values_faqs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='frequentlyaskedquestion',
            name='slug',
            field=models.SlugField(blank=True, default=None, unique=True),
        ),
    ]
