# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-08 19:06
from __future__ import unicode_literals

from django.db import migrations


def remove_program_courses(apps, schema_editor):
    ProgramCourse = apps.get_model('cms', 'ProgramCourse')
    ProgramCourse.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0027_semesterdate'),
    ]

    operations = [
        migrations.RunPython(remove_program_courses),
    ]
