# Generated by Django 2.1.2 on 2019-01-14 14:34

from django.db import migrations
import wagtail.contrib.table_block.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0033_remove_programpage_external_program_page_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='programtabpage',
            name='table',
            field=wagtail.core.fields.StreamField([('course_table', wagtail.contrib.table_block.blocks.TableBlock())], null=True),
        ),
    ]
