# Generated by Django 2.1.5 on 2019-03-01 07:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0021_image_file_hash'),
        ('cms', '0037_programlettersignatories'),
    ]

    operations = [
        migrations.AddField(
            model_name='programpage',
            name='program_letter_logo',
            field=models.ForeignKey(blank=True, help_text='Logo will be appeared on program letter. ', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
    ]
