# Generated by Django 2.1.11 on 2019-11-07 10:21

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0040_add_course_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseteamtabpage',
            name='administrators',
            field=wagtail.core.fields.StreamField([('administrator', wagtail.core.blocks.StructBlock([('name', wagtail.core.blocks.CharBlock(help_text='Name of the course team member.', max_length=100)), ('bio', wagtail.core.blocks.CharBlock(help_text='Short bio of course team member.', max_length=255)), ('image', wagtail.images.blocks.ImageChooserBlock(help_text='Image for the faculty member. Should be 385px by 385px.'))]))], blank=True),
        ),
        migrations.AlterField(
            model_name='courseteamtabpage',
            name='contributors',
            field=wagtail.core.fields.StreamField([('contributor', wagtail.core.blocks.StructBlock([('name', wagtail.core.blocks.CharBlock(help_text='Name of the course team member.', max_length=100)), ('bio', wagtail.core.blocks.CharBlock(help_text='Short bio of course team member.', max_length=255)), ('image', wagtail.images.blocks.ImageChooserBlock(help_text='Image for the faculty member. Should be 385px by 385px.'))]))], blank=True),
        ),
        migrations.AlterField(
            model_name='courseteamtabpage',
            name='instructors',
            field=wagtail.core.fields.StreamField([('instructors', wagtail.core.blocks.StructBlock([('name', wagtail.core.blocks.CharBlock(help_text='Name of the course team member.', max_length=100)), ('bio', wagtail.core.blocks.CharBlock(help_text='Short bio of course team member.', max_length=255)), ('image', wagtail.images.blocks.ImageChooserBlock(help_text='Image for the faculty member. Should be 385px by 385px.'))]))], blank=True),
        ),
        migrations.AlterField(
            model_name='courseteamtabpage',
            name='teaching_assistant',
            field=wagtail.core.fields.StreamField([('TAs', wagtail.core.blocks.StructBlock([('name', wagtail.core.blocks.CharBlock(help_text='Name of the course team member.', max_length=100)), ('bio', wagtail.core.blocks.CharBlock(help_text='Short bio of course team member.', max_length=255)), ('image', wagtail.images.blocks.ImageChooserBlock(help_text='Image for the faculty member. Should be 385px by 385px.'))]))], blank=True),
        ),
    ]
