# Generated by Django 2.1.11 on 2019-11-07 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0041_auto_20191107_1021'),
    ]

    operations = [
        migrations.RenameField(
            model_name='courseteamtabpage',
            old_name='teaching_assistant',
            new_name='teaching_assistants',
        ),
    ]
