# Generated by Django 2.1.11 on 2020-02-03 12:47

from django.db import migrations
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0046_courseteam_title_update'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseteamtabpage',
            name='administrators',
            field=wagtail.fields.StreamField([('administrator', wagtail.blocks.StructBlock([('name', wagtail.blocks.CharBlock(help_text='Name of the course team member.', max_length=100)), ('title', wagtail.blocks.RichTextBlock(features=['bold', 'italic'], help_text='Title of the course team member.', required=False)), ('bio', wagtail.blocks.TextBlock(help_text='Short bio of course team member.')), ('image', wagtail.images.blocks.ImageChooserBlock(help_text='Image for the faculty member. Should be 385px by 385px.'))]))], blank=True),
        ),
        migrations.AlterField(
            model_name='courseteamtabpage',
            name='contributors',
            field=wagtail.fields.StreamField([('contributor', wagtail.blocks.StructBlock([('name', wagtail.blocks.CharBlock(help_text='Name of the course team member.', max_length=100)), ('title', wagtail.blocks.RichTextBlock(features=['bold', 'italic'], help_text='Title of the course team member.', required=False)), ('bio', wagtail.blocks.TextBlock(help_text='Short bio of course team member.')), ('image', wagtail.images.blocks.ImageChooserBlock(help_text='Image for the faculty member. Should be 385px by 385px.'))]))], blank=True),
        ),
        migrations.AlterField(
            model_name='courseteamtabpage',
            name='instructors',
            field=wagtail.fields.StreamField([('instructors', wagtail.blocks.StructBlock([('name', wagtail.blocks.CharBlock(help_text='Name of the course team member.', max_length=100)), ('title', wagtail.blocks.RichTextBlock(features=['bold', 'italic'], help_text='Title of the course team member.', required=False)), ('bio', wagtail.blocks.TextBlock(help_text='Short bio of course team member.')), ('image', wagtail.images.blocks.ImageChooserBlock(help_text='Image for the faculty member. Should be 385px by 385px.'))]))], blank=True),
        ),
        migrations.AlterField(
            model_name='courseteamtabpage',
            name='teaching_assistants',
            field=wagtail.fields.StreamField([('TAs', wagtail.blocks.StructBlock([('name', wagtail.blocks.CharBlock(help_text='Name of the course team member.', max_length=100)), ('title', wagtail.blocks.RichTextBlock(features=['bold', 'italic'], help_text='Title of the course team member.', required=False)), ('bio', wagtail.blocks.TextBlock(help_text='Short bio of course team member.')), ('image', wagtail.images.blocks.ImageChooserBlock(help_text='Image for the faculty member. Should be 385px by 385px.'))]))], blank=True),
        ),
    ]
