# Generated by Django 2.2.13 on 2020-10-26 09:12

from django.db import migrations
import wagtail.contrib.table_block.blocks
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ("cms", "0048_convert_description_richtextfield_to_streamfield"),
    ]

    operations = [
        migrations.AlterField(
            model_name="benefitspage",
            name="content",
            field=wagtail.core.fields.StreamField(
                [
                    ("rich_text", wagtail.core.blocks.RichTextBlock()),
                    (
                        "image_with_link",
                        wagtail.core.blocks.StructBlock(
                            [
                                (
                                    "image",
                                    wagtail.images.blocks.ImageChooserBlock(
                                        help_text="The image to display.",
                                        label="Image",
                                        required=True,
                                    ),
                                ),
                                (
                                    "link",
                                    wagtail.core.blocks.URLBlock(
                                        help_text="Absolute URL to the image, like https://example.com/some_image.jpg",
                                        label="Link",
                                        required=True,
                                    ),
                                ),
                                (
                                    "align",
                                    wagtail.core.blocks.ChoiceBlock(
                                        choices=[
                                            ("center", "Center"),
                                            ("right", "Right"),
                                            ("left", "Left"),
                                        ],
                                        max_length=10,
                                    ),
                                ),
                                (
                                    "width",
                                    wagtail.core.blocks.IntegerBlock(required=False),
                                ),
                                (
                                    "height",
                                    wagtail.core.blocks.IntegerBlock(required=False),
                                ),
                            ],
                            blank=True,
                            help_text="Upload an image with a clickable link",
                        ),
                    ),
                    (
                        "benefits_table",
                        wagtail.contrib.table_block.blocks.TableBlock(
                            table_options={
                                "renderer": "html",
                                "startCols": 2,
                                "startRows": 3,
                            }
                        ),
                    ),
                ],
                blank=True,
                help_text="The content of the benefits page",
            ),
        ),
    ]
