# Generated by Django 2.2.28 on 2022-08-10 14:45

from django.conf import settings
from django.db import migrations
from django.db.models import F, Value
from django.db.models.functions import Concat

from ecommerce.constants import REFERENCE_NUMBER_PREFIX


def populate_order_ref_number(apps, schema_editor):
    """Populate historical orders' reference numbers"""
    Order = apps.get_model("ecommerce", "Order")

    Order.objects.filter(reference_number__isnull=True).update(
        reference_number=Concat(
            Value(REFERENCE_NUMBER_PREFIX),
            Value(settings.CYBERSOURCE_REFERENCE_PREFIX),
            Value("-"),
            F("id")
        )
    )


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0019_add_order_reference_number'),
    ]

    operations = [
        migrations.RunPython(populate_order_ref_number, migrations.RunPython.noop)
    ]
