# Generated by Django 2.2.28 on 2022-11-22 13:25

from django.db import migrations, models
from grades.api import completed_program
from django.contrib.auth.models import User
from courses.models import Program


def deactivate_invalid_program_letters(apps, schema_editor):
    """
    Analyze the Program letters and deactivate those that are invalid,
    e.g. A program letter is invalid if the program for that user is incomplete
    """

    MicromastersProgramCommendation = apps.get_model('grades', 'MicromastersProgramCommendation')

    all_program_letters = MicromastersProgramCommendation.objects.all()

    for program_letter in all_program_letters:
        user = User.objects.get(id=program_letter.user.id)
        program = Program.objects.get(id=program_letter.program.id)
        # Activate the program letter if the user has completed the program
        is_program_completed = completed_program(user=user, program=program)
        program_letter.is_active = is_program_completed

    MicromastersProgramCommendation.objects.bulk_update(all_program_letters, fields=['is_active'])


class Migration(migrations.Migration):
    dependencies = [
        ('grades', '0019_client_authorization_id_null'),
    ]

    operations = [
        migrations.AddField(
            model_name='micromastersprogramcommendation',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Indicates whether or not the program letter is active',
                                      verbose_name='is_active'),
        ),
        migrations.RunPython(deactivate_invalid_program_letters, migrations.RunPython.noop)

    ]
