# Generated by Django 5.2.9 on 2026-01-07 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_mitxonline_cache'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cachedcertificate',
            name='data',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='cachedcurrentgrade',
            name='data',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='cachedenrollment',
            name='data',
            field=models.JSONField(),
        ),
    ]
