# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-23 19:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financialaid', '0003_added_timestamps'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='financialaidaudit',
            name='date',
        ),
        migrations.RemoveField(
            model_name='financialaidaudit',
            name='table_changed',
        ),
    ]
