# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-26 17:15
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financialaid', '0003_added_timestamps'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financialaidaudit',
            name='data_after',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True),
        ),
        migrations.AlterField(
            model_name='financialaidaudit',
            name='data_before',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True),
        ),
    ]
