# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-29 00:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financialaid', '0011_temp_remove_rejected_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='financialaid',
            name='justification',
            field=models.TextField(null=True),
        ),
    ]
