# Generated by Django 1.9.8 on 2016-09-29 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financialaid', '0012_modify_documents_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='financialaid',
            name='justification',
            field=models.TextField(null=True),
        ),
    ]
