# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-28 18:57
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProctoredProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_on', models.DateTimeField(auto_now=True, db_index=True)),
                ('synced_on', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('first_name', models.TextField(blank=True, max_length=30, null=True)),
                ('last_name', models.CharField(blank=True, max_length=50, null=True)),
                ('address1', models.CharField(blank=True, max_length=40, null=True)),
                ('address2', models.CharField(blank=True, max_length=40, null=True)),
                ('address3', models.CharField(blank=True, max_length=40, null=True)),
                ('country', models.CharField(blank=True, max_length=3, null=True)),
                ('state_or_territory', models.CharField(blank=True, max_length=20, null=True)),
                ('city', models.CharField(blank=True, max_length=32, null=True)),
                ('postal_code', models.CharField(blank=True, max_length=16, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=35, null=True)),
                ('phone_country_code', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(999)])),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
