# Generated by Django 2.2.13 on 2020-11-23 22:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0016_examauthorization_exam_coupon_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamRunCoupon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('coupon_url', models.URLField()),
                ('used', models.BooleanField(default=False)),
                ('exam_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_run_coupons', to='exams.ExamRun')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
