# Generated by Django 2.2.13 on 2020-11-09 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0016_examauthorization_exam_coupon_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='examrun',
            name='passing_score',
            field=models.FloatField(default=0.5),
        ),
    ]
