# Generated by Django 2.2.13 on 2021-02-22 19:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0035_program_attempts'),
        ('exams', '0017_examrun_passing_score'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamRunCoupon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('edx_exam_course_key', models.CharField(max_length=30)),
                ('coupon_url', models.URLField()),
                ('coupon_code', models.CharField(max_length=30)),
                ('expiration_date', models.DateTimeField()),
                ('is_taken', models.BooleanField(default=False)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_exam_coupons', to='courses.Course')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
