# Generated by Django 2.2.13 on 2021-02-25 15:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0018_examruncoupon'),
    ]

    operations = [
        migrations.AddField(
            model_name='examauthorization',
            name='exam_coupon',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='exams.ExamRunCoupon'),
        ),
    ]
