# Generated by Django 2.2.24 on 2021-11-15 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0019_examauthorization_exam_coupon'),
    ]

    operations = [
        migrations.AddField(
            model_name='examrun',
            name='edx_exam_course_key',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
