# Generated by Django 1.9.7 on 2016-06-29 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_program_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='courserun',
            name='upgrade_deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
