# Generated by Django 1.9.10 on 2016-11-07 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0017_indexes_in_courserun'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ('position_in_program',)},
        ),
    ]
