# Generated by Django 1.10.3 on 2016-11-10 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0018_course_default_ordering'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='courserun',
            options={'ordering': ('start_date',)},
        ),
    ]
