# Generated by Django 2.2.13 on 2021-01-20 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0034_program_topics'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='exam_attempts_first_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='program',
            name='exam_attempts_second_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
