# Generated by Django 2.2.24 on 2021-07-27 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0035_program_attempts'),
    ]

    operations = [
        migrations.AddField(
            model_name='courserun',
            name='courseware_backend',
            field=models.CharField(choices=[('mitxonline', 'mitxonline'), ('edxorg', 'edxorg')], default='edxorg', max_length=32),
        ),
    ]
