# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-05 19:37
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0003_remove_percolatequery'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='percolatequery',
            name='query',
        ),
        migrations.AddField(
            model_name='percolatequery',
            name='filters',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=[]),
            preserve_default=False,
        ),
    ]
