# Generated by Django 2.2.28 on 2025-12-12 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0005_percolatequery_is_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='percolatequery',
            name='source_type',
            field=models.CharField(choices=[('automatic_email_type', 'automatic_email_type')], max_length=255),
        ),
    ]
