# Generated by Django 1.9.8 on 2016-09-26 20:28
# Modified: Removed FinancialAidEmailAudit model (financialaid app removed)
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = []
