# Generated by Django 1.9.8 on 2016-09-28 18:29
# Modified: Removed FinancialAidEmailAudit updates (financialaid app removed)
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0001_initial'),
    ]

    operations = []
