# Generated by Django 5.2.9 on 2026-01-16 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0008_partnerschool'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FinancialAidEmailAudit',
        ),
    ]
